name: Build & Deploy
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - run: npm install
      - run: npm run build
      - name: Deploy
        if: github.event_name != 'pull_request' 
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public
