name: Build & Deploy
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch all history to get correct updated date
          submodules: true
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm ci
      - run: npm run build
      - name: Validate public HTML 
        run: |
          grep -qr --include '*.html' '[^[:space:]]' public/
          npm run validate-public
      - name: Deploy
        if: github.event_name != 'pull_request' 
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public
